name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        image:
          - ubuntu:rolling
          - ubuntu:20.04
          - ubuntu:18.04
          - fedora:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.image, 'ubuntu:')
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gtk-doc-tools libgirepository1.0-dev libglib2.0-dev libjson-glib-dev libsoup2.4-dev meson ninja-build qtbase5-dev qtdeclarative5-dev valac

      - name: Install dependencies (Fedora)
        if: startsWith(matrix.image, 'fedora:')
        run: |
          dnf install -y gcc gcc-c++ gobject-introspection-devel glib2-devel gtk-doc json-glib-devel libsoup-devel meson ninja-build qt5-qtbase-devel qt5-qtdeclarative-devel redhat-rpm-config vala

      - name: Build
        run: |
          meson _build
          ninja -C _build
          ninja -C _build snapd-glib-doc

      - name: Test
        run: ninja -C _build test
